apiVersion: v1
kind: Pod
metadata:
  name: debugxx // use your pod name
  namespace: kube-system
spec:
  containers:
  - name: debug0
    image: mcr.microsoft.com/cbl-mariner/base/core:2.0
    imagePullPolicy: IfNotPresent
    command:
    - sh
    - -c
    - sleep 10000000
  restartPolicy: Always
  hostNetwork: true
  tolerations:
  - key: "test"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"
  nodeSelector:
    kubernetes.io/hostname: aks-nodepool1-37663765-vmss000000